### PR TITLE
#124 fix node version runtime error

### LINKED ISSUE #124: Fix node version runtime error
Pushing a requisition from `v0.2.1` throws the following error:

```
"error": {
    "code": "ERROR_RUNTIME",
    "message": "Error: Unexpected runtime error occurred. indicators.map(...).flat is not a function",
    "wasDeleted": false,
    "deleteError": {
       "code": "ERROR_SERVER",
       "message": "Error: During deleteRequisition, Unknown Server Error - HTTP CODE: 500"
    }
},
```

`.flat()` is supported by `node>=11` (currently building for `node8`. Babel presets may need updating, but quickest solution is to remove use of `.flat`.

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #124.

Error was thrown by `.flat()`, refactored to use `.reduce()`.

All tests passing.

### CODE REVIEW

File: src/requisitionMerge.js [hunk 1]
```diff
@@ -78,7 +78,7 @@ const createRegimenLineItems = regimenData => {
       });
       return indicatorRegimenLineItems;
     })
-    .flat();
+    .reduce((acc, indicatorRegimenLineItems) => [...acc, ...indicatorRegimenLineItems]);
```
Comment (josh-griffin) [inline src/requisitionMerge.js]: `.reduce((acc, indicatorRegimenLineItems) => [...acc, ...indicatorRegimenLineItems]);`
`.reduce((acc, indicatorRegimenLineItems) => [...acc, ...indicatorRegimenLineItems], []`);

**Review by josh-griffin — CHANGES_REQUESTED** [review]

**Review by josh-griffin — APPROVED** [review]

File: src/requisitionMerge.js (hunk 1 above)
Comment (wlthomson) [reply src/requisitionMerge.js]: b10f56f. 

cookie
