### PR TITLE
#142 map regimen value comment columns

### LINKED ISSUE #142: Map mSupply value, comment regimen columns to eSIGL indicators
After user testing in IC, some indicator columns are not correctly matching.

#### Background

The mSupply indicator columns need to be mapped to the eSIGL coiumns. Some mappings are broken/out-of-date.

mSupply has the following minimal indicator columns:

- `regimen_value`
- `regimen_comment`

####  Implementation

Nothing difficult here, just a mapping between the mSupply column codes and the eSIGL column codes. Assuming the VM is up-to-date:

- `regimen_value` <-> `patientsOnTreatment`
- `regimen_comment` <-> `remarks`

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #142.

### CODE REVIEW

File: src/requisitionMerge.js [hunk 1]
```diff
@@ -110,11 +110,6 @@ const minimalOutgoingLine = outgoingLine => ({
   requiredItem: !outgoingLine.skipped,
 });
 
-const getConsumption = incomingLine => {
```
Comment (wlthomson) [inline src/requisitionMerge.js]: Not sure what's going on here. Just ignore the duplicate changes from #143, think it's due to a force push due to a git config issue.

**Review by josh-griffin — APPROVED** [review]
